### ISSUE TITLE
$ScrollSmoother.kill() doesn't exist

### ISSUE THREAD

**Issue by urbgimtam** [hypernym-studio/nuxt-gsap#59]
### Steps to Reproduce

Trying to automate killing and creation of ScrollSmoother by using nuxt hooks in a plugin, because .refresh() doesn't seem to recalculate parallax effects.

```
// ./plugins/scrollsmoother,ts

export default defineNuxtPlugin((nuxtApp) => {

  const createScroller = () => nuxtApp.$ScrollSmoother.create({
      autoResize: true,
      smooth: 2, 
      effects: true
    })


  // create ScrollSmoother in app mounted
  nuxtApp.hook("app:mounted", () => {
    createScroller()
  })


  // refresh or kill+create on route change
  nuxtApp.hook("page:finish", (e) => {
    // $ScrollSmoother.refresh() exists, but doesn't recalculate all data for parallax, etc.
    nuxtApp.$ScrollSmoother.refresh()

    // $ScrollSmoother.kill() does not exist, but GSAP docs recommend it
    nuxtApp.$ScrollSmoother.kill()

    // Logging the nuxtApp, we can see $ScrollSmoother functions, but 'kill' is not present.
    console.log('nuxtApp: ', nuxtApp);

  })
})
```

### Current Behavior

Seems that the ScrollSmoother.kill function is not available on the module.

### Expected Behavior

Expected that all GSAP functions would be available on the module.

### Additional Details

Nuxt 3.9.0
Vue 3.4.1

Love the module anyway! I've given you a star

**Comment by ivodolenc** [comment]
Hi, thanks for your interest in the module.

Can you try importing Gsap and SmoothScroller manually and see if that works?

```ts
import { gsap } from 'gsap'
import { ScrollSmoother } from 'gsap/ScrollSmoother'
gsap.registerPlugin(ScrollSmoother)

export default defineNuxtPlugin((nuxtApp) => {
  // ...
})
```

If the result is the same (function not working), then something with the import process is not right on your end.

If all works as expected, then the problem is with the module (or nuxt internal bug).

Also note that Nuxt's plugin must be client-side. And SmoothScroller is a premium plugin, so pay attention to that as well.

**Comment by urbgimtam** [comment]
Sorry, you are correct.

I didn't read the GSAP documents properly, it seems. https://gsap.com/docs/v3/Plugins/ScrollSmoother/kill()

.kill() is a property of the instance created, not of ScrollSmoother itself.
So, its in fact accessible on the instance.

```vue
const instance = nuxtApp.$ScrollSmoother.create({...})
instance.kill() // exists
```

Nevertheless, in the end I solved my issue, due to the fact that GSAP ScrollSmoother can only have 1 instance at any given time (as stated here: https://gsap.com/docs/v3/Plugins/ScrollSmoother/static.get()/).

This means we can create it as many times as needed. By defining this custom plugin, I can now just have this 1 file, and nested parallax always works between route changes / pages.

```vue
// ./plugins/scrollsmoother.ts

export default defineNuxtPlugin((nuxtApp) => {

  
  nuxtApp.hook('page:finish', () => {
      // "page:finish" is triggered when a page ends loading, on client-side.

      const instance = nuxtApp.$ScrollSmoother.create({
        ScrollTrigger: {
          invalidateOnRefresh: true,
        },
        ignoreMobileResize: true,
        autoResize: true,
        smooth: 2,
        effects: true,
      })

      return instance
    }
})
```

Would still prefer to get the current instance and refresh it or kill it, but I can't catch the instance before creating...
But at least, this way it works for now. Thank you again 🙏

(I do have the premium gsap. Without it, obviously doesn't work)

**Comment by ivodolenc** [comment]
Ok, no problem, glad you solved it 👍
